"""
Dados mockados realistas para o frontend funcionar antes do backend real.
Todos os jogos, análises, bingos e alertas são fictícios.
"""

from datetime import datetime, timedelta, timezone

_now = datetime.now(timezone.utc)
_today = _now.replace(hour=0, minute=0, second=0, microsecond=0)


def _dt(days=0, hour=15, minute=0):
    return (_today + timedelta(days=days)).replace(hour=hour, minute=minute)


MOCK_GAMES = [
    # ----- AO VIVO -----
    {
        "id": 1,
        "external_id": "ext-001",
        "league": "Brasileirão Série A",
        "country": "Brasil",
        "home_team": "Flamengo",
        "away_team": "Palmeiras",
        "home_logo": "https://media.api-sports.io/football/teams/127.png",
        "away_logo": "https://media.api-sports.io/football/teams/121.png",
        "datetime": _dt(0, 16, 0).isoformat(),
        "status": "live",
        "home_score": 1,
        "away_score": 0,
        "clock": "67",
        "period": 2,
        "home_possession": 54.2,
        "away_possession": 45.8,
        "home_shots": 8,
        "away_shots": 5,
        "home_corners": 4,
        "away_corners": 3,
        "home_yellow_cards": 1,
        "away_yellow_cards": 2,
        "has_odds": True,
        "odds_home": 2.10,
        "odds_draw": 3.20,
        "odds_away": 3.50,
    },
    {
        "id": 2,
        "external_id": "ext-002",
        "league": "La Liga",
        "country": "Espanha",
        "home_team": "Real Madrid",
        "away_team": "Barcelona",
        "home_logo": "https://media.api-sports.io/football/teams/541.png",
        "away_logo": "https://media.api-sports.io/football/teams/529.png",
        "datetime": _dt(0, 17, 0).isoformat(),
        "status": "live",
        "home_score": 2,
        "away_score": 2,
        "clock": "78",
        "period": 2,
        "home_possession": 48.0,
        "away_possession": 52.0,
        "home_shots": 11,
        "away_shots": 9,
        "home_corners": 6,
        "away_corners": 5,
        "home_yellow_cards": 2,
        "away_yellow_cards": 1,
        "has_odds": True,
        "odds_home": 2.30,
        "odds_draw": 3.10,
        "odds_away": 3.00,
    },
    # ----- HOJE -----
    {
        "id": 3,
        "external_id": "ext-003",
        "league": "Brasileirão Série A",
        "country": "Brasil",
        "home_team": "Corinthians",
        "away_team": "São Paulo",
        "home_logo": "https://media.api-sports.io/football/teams/131.png",
        "away_logo": "https://media.api-sports.io/football/teams/126.png",
        "datetime": _dt(0, 19, 30).isoformat(),
        "status": "scheduled",
        "home_score": None,
        "away_score": None,
        "clock": None,
        "period": 0,
        "home_possession": None,
        "away_possession": None,
        "home_shots": 0,
        "away_shots": 0,
        "home_corners": 0,
        "away_corners": 0,
        "home_yellow_cards": 0,
        "away_yellow_cards": 0,
        "has_odds": True,
        "odds_home": 2.75,
        "odds_draw": 3.00,
        "odds_away": 2.60,
    },
    {
        "id": 4,
        "external_id": "ext-004",
        "league": "CONMEBOL Libertadores",
        "country": "América do Sul",
        "home_team": "River Plate",
        "away_team": "Boca Juniors",
        "home_logo": "https://media.api-sports.io/football/teams/1057.png",
        "away_logo": "https://media.api-sports.io/football/teams/1058.png",
        "datetime": _dt(0, 21, 0).isoformat(),
        "status": "scheduled",
        "home_score": None,
        "away_score": None,
        "clock": None,
        "period": 0,
        "home_possession": None,
        "away_possession": None,
        "home_shots": 0,
        "away_shots": 0,
        "home_corners": 0,
        "away_corners": 0,
        "home_yellow_cards": 0,
        "away_yellow_cards": 0,
        "has_odds": True,
        "odds_home": 2.20,
        "odds_draw": 3.10,
        "odds_away": 3.40,
    },
    {
        "id": 5,
        "external_id": "ext-005",
        "league": "Premier League",
        "country": "Inglaterra",
        "home_team": "Manchester City",
        "away_team": "Arsenal",
        "home_logo": "https://media.api-sports.io/football/teams/50.png",
        "away_logo": "https://media.api-sports.io/football/teams/42.png",
        "datetime": _dt(0, 16, 0).isoformat(),
        "status": "scheduled",
        "home_score": None,
        "away_score": None,
        "clock": None,
        "period": 0,
        "home_possession": None,
        "away_possession": None,
        "home_shots": 0,
        "away_shots": 0,
        "home_corners": 0,
        "away_corners": 0,
        "home_yellow_cards": 0,
        "away_yellow_cards": 0,
        "has_odds": True,
        "odds_home": 1.85,
        "odds_draw": 3.50,
        "odds_away": 4.20,
    },
    {
        "id": 6,
        "external_id": "ext-006",
        "league": "Serie A",
        "country": "Itália",
        "home_team": "Inter de Milão",
        "away_team": "AC Milan",
        "home_logo": "https://media.api-sports.io/football/teams/505.png",
        "away_logo": "https://media.api-sports.io/football/teams/489.png",
        "datetime": _dt(0, 18, 45).isoformat(),
        "status": "scheduled",
        "home_score": None,
        "away_score": None,
        "clock": None,
        "period": 0,
        "home_possession": None,
        "away_possession": None,
        "home_shots": 0,
        "away_shots": 0,
        "home_corners": 0,
        "away_corners": 0,
        "home_yellow_cards": 0,
        "away_yellow_cards": 0,
        "has_odds": True,
        "odds_home": 2.15,
        "odds_draw": 3.20,
        "odds_away": 3.30,
    },
    # ----- AMANHÃ -----
    {
        "id": 7,
        "external_id": "ext-007",
        "league": "Brasileirão Série A",
        "country": "Brasil",
        "home_team": "Atlético Mineiro",
        "away_team": "Fluminense",
        "home_logo": "https://media.api-sports.io/football/teams/1062.png",
        "away_logo": "https://media.api-sports.io/football/teams/119.png",
        "datetime": _dt(1, 20, 0).isoformat(),
        "status": "scheduled",
        "home_score": None,
        "away_score": None,
        "clock": None,
        "period": 0,
        "home_possession": None,
        "away_possession": None,
        "home_shots": 0,
        "away_shots": 0,
        "home_corners": 0,
        "away_corners": 0,
        "home_yellow_cards": 0,
        "away_yellow_cards": 0,
        "has_odds": True,
        "odds_home": 1.95,
        "odds_draw": 3.30,
        "odds_away": 3.80,
    },
    {
        "id": 8,
        "external_id": "ext-008",
        "league": "La Liga",
        "country": "Espanha",
        "home_team": "Atlético de Madrid",
        "away_team": "Sevilla",
        "home_logo": "https://media.api-sports.io/football/teams/530.png",
        "away_logo": "https://media.api-sports.io/football/teams/536.png",
        "datetime": _dt(1, 16, 0).isoformat(),
        "status": "scheduled",
        "home_score": None,
        "away_score": None,
        "clock": None,
        "period": 0,
        "home_possession": None,
        "away_possession": None,
        "home_shots": 0,
        "away_shots": 0,
        "home_corners": 0,
        "away_corners": 0,
        "home_yellow_cards": 0,
        "away_yellow_cards": 0,
        "has_odds": True,
        "odds_home": 1.75,
        "odds_draw": 3.60,
        "odds_away": 4.80,
    },
    # ----- ENCERRADOS -----
    {
        "id": 9,
        "external_id": "ext-009",
        "league": "Brasileirão Série A",
        "country": "Brasil",
        "home_team": "Santos",
        "away_team": "Grêmio",
        "home_logo": "https://media.api-sports.io/football/teams/130.png",
        "away_logo": "https://media.api-sports.io/football/teams/119.png",
        "datetime": _dt(-1, 19, 0).isoformat(),
        "status": "finished",
        "home_score": 2,
        "away_score": 1,
        "clock": "90",
        "period": 2,
        "home_possession": 51.0,
        "away_possession": 49.0,
        "home_shots": 12,
        "away_shots": 7,
        "home_corners": 6,
        "away_corners": 4,
        "home_yellow_cards": 2,
        "away_yellow_cards": 3,
        "has_odds": True,
        "odds_home": 2.40,
        "odds_draw": 3.10,
        "odds_away": 2.90,
    },
    {
        "id": 10,
        "external_id": "ext-010",
        "league": "Premier League",
        "country": "Inglaterra",
        "home_team": "Liverpool",
        "away_team": "Chelsea",
        "home_logo": "https://media.api-sports.io/football/teams/40.png",
        "away_logo": "https://media.api-sports.io/football/teams/49.png",
        "datetime": _dt(-1, 17, 0).isoformat(),
        "status": "finished",
        "home_score": 3,
        "away_score": 1,
        "clock": "90",
        "period": 2,
        "home_possession": 58.0,
        "away_possession": 42.0,
        "home_shots": 15,
        "away_shots": 6,
        "home_corners": 8,
        "away_corners": 3,
        "home_yellow_cards": 1,
        "away_yellow_cards": 2,
        "has_odds": True,
        "odds_home": 1.90,
        "odds_draw": 3.60,
        "odds_away": 4.00,
    },
]

MOCK_ANALYSES = {
    1: {
        "id": 1,
        "game_id": 1,
        "resultado_previsto": "Casa",
        "confianca": "ALTA",
        "resultado_json": {
            "r": "Casa",
            "c": "ALTA",
            "just": "Flamengo tem melhor aproveitamento em casa nesta temporada e o Palmeiras vem de 2 derrotas fora.",
            "ins": "Histórico recente favorece o time da casa em confrontos diretos no Maracanã.",
            "fc": "VVDVE",
            "ff": "DVVDD",
            "fca": 8.2,
            "ffo": 6.8,
            "fav": "Flamengo",
        },
        "gols_json": {
            "mk": "Mais de 2.5",
            "cf": "MEDIA",
            "te": "2.8",
            "am": "Sim",
            "nt": "Ambos times têm ataque forte e defesas pressionadas neste clássico.",
        },
        "escanteios_json": {"mk": "Mais de 9.5", "cf": "ALTA", "te": "10.3"},
        "cartoes_json": {"mk": "Mais de 3.5", "cf": "MEDIA", "te": "3.8"},
        "placar_json": {
            "mg": 5,
            "st": "Aberto",
            "pls": [
                {"p": "2-1", "v": "22%"},
                {"p": "1-0", "v": "18%"},
                {"p": "2-0", "v": "15%"},
            ],
        },
        "combinacoes_json": {
            "conservador": "Flamengo Vence + Mais de 1.5 gols",
            "moderado": "Flamengo Vence + Ambas marcam + Mais de 2.5",
            "ousado": "Flamengo Vence + Mais de 3.5 + Escanteios +10.5",
        },
        "created_at": _now.isoformat(),
    },
    2: {
        "id": 2,
        "game_id": 2,
        "resultado_previsto": "Empate",
        "confianca": "MEDIA",
        "resultado_json": {
            "r": "Empate",
            "c": "MEDIA",
            "just": "El Clásico historicamente equilibrado. Ambos times em fase similar na temporada.",
            "ins": "Última vez que se enfrentaram no Santiago Bernabéu terminou 1-1.",
            "fc": "VEVVD",
            "ff": "VVDEV",
            "fca": 8.5,
            "ffo": 9.0,
            "fav": "Barcelona",
        },
        "gols_json": {
            "mk": "Mais de 2.5",
            "cf": "ALTA",
            "te": "3.2",
            "am": "Sim",
            "nt": "Os dois melhores ataques da liga frente a frente.",
        },
        "escanteios_json": {"mk": "Mais de 10.5", "cf": "MEDIA", "te": "11.0"},
        "cartoes_json": {"mk": "Mais de 4.5", "cf": "ALTA", "te": "5.1"},
        "placar_json": {
            "mg": 5,
            "st": "Aberto",
            "pls": [
                {"p": "2-2", "v": "19%"},
                {"p": "1-1", "v": "17%"},
                {"p": "2-1", "v": "14%"},
            ],
        },
        "combinacoes_json": {
            "conservador": "Empate ou Barcelona Vence + Mais de 2.5",
            "moderado": "Ambas marcam + Mais de 3.5 gols",
            "ousado": "Placar exato 2-2 + Ambas marcam",
        },
        "created_at": _now.isoformat(),
    },
    3: {
        "id": 3,
        "game_id": 3,
        "resultado_previsto": "Fora",
        "confianca": "MEDIA",
        "resultado_json": {
            "r": "Fora",
            "c": "MEDIA",
            "just": "São Paulo vem em sequência invicta fora de casa e o Corinthians tem aproveitamento abaixo do esperado como mandante.",
            "ins": "São Paulo não perde para o Corinthians há 4 jogos consecutivos.",
            "fc": "DDVDD",
            "ff": "VVVEV",
            "fca": 5.5,
            "ffo": 7.8,
            "fav": "São Paulo",
        },
        "gols_json": {
            "mk": "Menos de 2.5",
            "cf": "MEDIA",
            "te": "1.9",
            "am": "Não",
            "nt": "Jogos entre esses times costumam ser táticos e truncados.",
        },
        "escanteios_json": {"mk": "Menos de 9.5", "cf": "ALTA", "te": "8.7"},
        "cartoes_json": {"mk": "Mais de 3.5", "cf": "ALTA", "te": "4.2"},
        "placar_json": {
            "mg": 5,
            "st": "Aberto",
            "pls": [
                {"p": "0-1", "v": "21%"},
                {"p": "1-1", "v": "18%"},
                {"p": "0-2", "v": "12%"},
            ],
        },
        "combinacoes_json": {
            "conservador": "São Paulo não perde + Menos de 2.5 gols",
            "moderado": "São Paulo Vence + Menos de 2.5",
            "ousado": "São Paulo Vence + 0 a 0 no 1° tempo + Mais de 3.5 cartões",
        },
        "created_at": _now.isoformat(),
    },
}

MOCK_BINGOS = [
    {
        "id": 1,
        "name": "Combo Sábado Premium",
        "category": "conservador",
        "tier": "seguro",
        "total_odd": 4.85,
        "confidence_pct": 78,
        "is_active": True,
        "created_at": _now.isoformat(),
        "selections": [
            {
                "home": "Flamengo",
                "away": "Palmeiras",
                "league": "Brasileirão Série A",
                "datetime": _dt(0, 16, 0).isoformat(),
                "market_label": "Flamengo Vence",
                "odd": 2.10,
                "confidence": "ALTA",
                "sub_picks": [
                    {"market_label": "Mais de 1.5 gols", "odd": 1.40},
                ],
            },
            {
                "home": "Manchester City",
                "away": "Arsenal",
                "league": "Premier League",
                "datetime": _dt(0, 16, 0).isoformat(),
                "market_label": "Manchester City Vence",
                "odd": 1.85,
                "confidence": "ALTA",
                "sub_picks": [
                    {"market_label": "Mais de 2.5 gols", "odd": 1.65},
                ],
            },
        ],
    },
    {
        "id": 2,
        "name": "Super Gols Europeu",
        "category": "moderado",
        "tier": "moderado",
        "total_odd": 9.20,
        "confidence_pct": 62,
        "is_active": True,
        "created_at": _now.isoformat(),
        "selections": [
            {
                "home": "Real Madrid",
                "away": "Barcelona",
                "league": "La Liga",
                "datetime": _dt(0, 17, 0).isoformat(),
                "market_label": "Ambas marcam",
                "odd": 1.60,
                "confidence": "ALTA",
                "sub_picks": [
                    {"market_label": "Mais de 2.5 gols", "odd": 1.55},
                ],
            },
            {
                "home": "Inter de Milão",
                "away": "AC Milan",
                "league": "Serie A",
                "datetime": _dt(0, 18, 45).isoformat(),
                "market_label": "Ambas marcam",
                "odd": 1.70,
                "confidence": "MEDIA",
                "sub_picks": [
                    {"market_label": "Mais de 2.5 gols", "odd": 1.80},
                ],
            },
        ],
    },
    {
        "id": 3,
        "name": "Clássico Máximo",
        "category": "maximo",
        "tier": "risco",
        "total_odd": 18.50,
        "confidence_pct": 44,
        "is_active": True,
        "created_at": _now.isoformat(),
        "selections": [
            {
                "home": "Flamengo",
                "away": "Palmeiras",
                "league": "Brasileirão Série A",
                "datetime": _dt(0, 16, 0).isoformat(),
                "market_label": "Flamengo Vence + Mais de 2.5",
                "odd": 3.50,
                "confidence": "MEDIA",
                "sub_picks": [
                    {"market_label": "Mais de 3.5 gols", "odd": 2.80},
                ],
            },
            {
                "home": "River Plate",
                "away": "Boca Juniors",
                "league": "CONMEBOL Libertadores",
                "datetime": _dt(0, 21, 0).isoformat(),
                "market_label": "River Plate Vence",
                "odd": 2.20,
                "confidence": "BAIXA",
                "sub_picks": [
                    {"market_label": "Mais de 2.5 gols", "odd": 2.10},
                ],
            },
        ],
    },
]

MOCK_STATS = [
    {
        "league": "Geral",
        "total": 248,
        "correct": 173,
        "accuracy_pct": 69.8,
        "by_confidence": {
            "ALTA": {"total": 82, "correct": 68, "pct": 82.9},
            "MEDIA": {"total": 110, "correct": 76, "pct": 69.1},
            "BAIXA": {"total": 56, "correct": 29, "pct": 51.8},
        },
    },
    {
        "league": "Brasileirão Série A",
        "total": 96,
        "correct": 71,
        "accuracy_pct": 74.0,
        "by_confidence": {
            "ALTA": {"total": 34, "correct": 30, "pct": 88.2},
            "MEDIA": {"total": 42, "correct": 30, "pct": 71.4},
            "BAIXA": {"total": 20, "correct": 11, "pct": 55.0},
        },
    },
    {
        "league": "Premier League",
        "total": 52,
        "correct": 36,
        "accuracy_pct": 69.2,
        "by_confidence": {
            "ALTA": {"total": 18, "correct": 15, "pct": 83.3},
            "MEDIA": {"total": 24, "correct": 16, "pct": 66.7},
            "BAIXA": {"total": 10, "correct": 5, "pct": 50.0},
        },
    },
    {
        "league": "La Liga",
        "total": 48,
        "correct": 33,
        "accuracy_pct": 68.8,
        "by_confidence": {
            "ALTA": {"total": 16, "correct": 13, "pct": 81.3},
            "MEDIA": {"total": 22, "correct": 15, "pct": 68.2},
            "BAIXA": {"total": 10, "correct": 5, "pct": 50.0},
        },
    },
]

MOCK_LIVE_ALERTS = [
    {
        "id": 1,
        "game_id": 1,
        "market": "Próximo gol - Casa",
        "signal": "Flamengo domina o jogo com 54% de posse e criou 3 chances claras nos últimos 10 minutos.",
        "confidence": "ALTA",
        "triggered_at": _now.isoformat(),
        "is_active": True,
        "pressure_data": {
            "possession": "54%",
            "shots": "8",
            "corners": "4",
            "pressure_score": "8.2/10",
            "green_condition": "Pressão alta sustentada + Escanteios acumulados",
        },
    },
    {
        "id": 2,
        "game_id": 2,
        "market": "Mais um gol na partida",
        "signal": "Real Madrid e Barcelona estão em ritmo intenso. Ambos buscam a virada no 2° tempo.",
        "confidence": "ALTA",
        "triggered_at": _now.isoformat(),
        "is_active": True,
        "pressure_data": {
            "possession": "48%/52%",
            "shots": "11/9",
            "corners": "6/5",
            "pressure_score": "9.1/10",
            "green_condition": "Alta intensidade + Ambos com posse equilibrada",
        },
    },
]

MOCK_SUBSCRIPTION_PLANS = [
    {
        "id": 1,
        "name": "Semanal",
        "description": "Acesso completo por 7 dias",
        "price_cents": 1990,
        "interval": "weekly",
        "module_access": {"jogos": True, "aovivo": True, "bingos": True, "segmentos": True},
        "is_active": True,
    },
    {
        "id": 2,
        "name": "Quinzenal",
        "description": "Acesso completo por 15 dias",
        "price_cents": 2990,
        "interval": "biweekly",
        "module_access": {"jogos": True, "aovivo": True, "bingos": True, "segmentos": True},
        "is_active": True,
    },
    {
        "id": 3,
        "name": "Mensal",
        "description": "Acesso completo por 30 dias",
        "price_cents": 4990,
        "interval": "monthly",
        "module_access": {"jogos": True, "aovivo": True, "bingos": True, "segmentos": True},
        "is_active": True,
    },
]
